"""
Test Gemini API mode.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

from llm.event_generator import generate_event
import json


def test_gemini_mode():
    """Test event generation with Gemini API."""
    print("Testing LLM module with Gemini API...")
    print("-" * 50)

    # Test day 4 (will use Gemini API)
    print("\nDay 4 (Generated by Gemini API):")
    event = generate_event(4)
    print(json.dumps(event, indent=2, ensure_ascii=False))
    print("-" * 50)


if __name__ == "__main__":
    test_gemini_mode()
